version: '3.7'

services:
  ### PHP-FPM Container #######################################
  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/php-fpm/php8.2.ini:/usr/local/etc/php/php.ini
      - ./docker/php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    expose:
      - "9000"
      - "9001"
    extra_hosts:
      # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      # IMPORTANT: Set the Remote Interpreter entry matching name to `laravel`
      - PHP_IDE_CONFIG=serverName=localhost
      - XDEBUG_CONFIG=remote_host=${DOCKER_HOST_IP}
    networks:
      - app-network
    restart: on-failure

  ### Nginx Server Container ##################################
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM=php-fpm
    volumes:
      - .:/var/www/html
      - ./docker/nginx/timeout.conf:/etc/nginx/conf.d/timeout.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: on-failure
    ports:
      - "80:80"
    networks:
      - app-network

  ### Redis ################################################
  redis:
    build:
      context: ./docker/redis
    volumes:
      - ./docker/redis:/data
    ports:
      - "6379:6379"
    networks:
      - app-network

  ### PostgreSQL Server Container ##################################
  postgres:
    build:
      context: ./docker/postgres
    volumes:
      - contrato:/var/lib/postgresql/data
    ports:
      - "5438:5432"  # Mapeamento de portas correto
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  contrato:
    driver: local
  contrato-mysql-data:
    driver: local
